### PR TITLE
HeroChat 5.7 Compatibility

### PR DESCRIPTION
**Pull request by AKPWebDesign**
This updates the plugin to work with HeroChat 5.7, building against Spigot 1.11.1.

### CODE REVIEW

**Comment by dequis** [comment]
>HeroChat's repo has been down for a while, so has been installed locally (again).

Oh come on, really? Also maybe I should just push those first two commits myself

**Comment by AKPWebDesign** [comment]
> Oh come on, really?  

Yeah... 😑

> Also maybe I should just push those first two commits myself  

If you'd like. Feel free to, and I can rebase once you've done it.

**Comment by dequis** [comment]
Pushed

**Comment by AKPWebDesign** [comment]
Think that should get it. Also reworded my commit to include that it fixes that issue, since I noticed that there's an issue. Also I'm doing this all from mobile so let me know if there are any problems.

**Comment by dequis** [comment]
many tanks

**Pull request merged**
